# controllers.yaml
arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [hip, shoulder, elbow, wrist]
  gains:
    hip: {p: 1000.0, d: 100.0}
    shoulder: {p: 1000.0, d: 100.0}
    elbow: {p: 800.0, d: 80.0}
    wrist: {p: 500.0, d: 50.0}

    
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
